INSERT INTO PRODUTO(NOME, VALOR) VALUES('GELADEIRA', 4999.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('SOFÁ', 2345.89);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('ARMÁRIO', 345.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('CADEIRA', 299.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('CAMA BOX', 800.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('CELULAR', 1200.90);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('PNEU', 390.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('TELEVISÃO', 4.654);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('VIDEO-GAME', 5.000);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('SOM', 3.988);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('FOGAO', 800.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('MICROONDAS', 750.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('MESA', 600.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('NOTEBOOK', 3450.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('CADEIRA GAMER', 1045.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('FONE OUVIDO', 299.99);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('IPHONE 12', 7700.99);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('AR CONDICIONADO', 1200.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('MAQUINA DE LAVAR ', 1700.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('LIVRO', 89.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('DRONE', 345.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('IMPRESSORA', 599.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('LIQUIDIFICADOR', 89.90);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('TABLET', 899.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('BICICLETA', 450.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('VENTILADOR', 95.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('BONECA', 99.00);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('MOCHILA', 199.90);
INSERT INTO PRODUTO(NOME, VALOR) VALUES('BLUSA', 89.90);


INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Maria Rodrigue Martins', '123.543.987-90', 'maria@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('João Augusto Cersar', '084.332.196-26', 'joao@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Valentina Manuela Silva', '327.327.472-70', 'valentina@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Guilherme Enrico Daniel Figueiredo', '248.669.319-06', 'guilherme@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Jéssica Helena da Conceição', '272.839.335-49', 'jessica@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Raul Mateus Moura', '477.619.930-09', 'raul@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Nicolas Cauã Araújo', '154.331.069-93', 'nicolas@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Isadora Evelyn Carolina Silveira', '932.956.941-25', 'isadora@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Caroline Sarah Silvana Pires', '477.775.029-99', 'carol@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Lucas Luan Yuri da Paz', '247.346.367-02', 'lucas@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Thiago Cauã Freitas', '375.579.488-82', 'tiago@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Sérgio Kauê Benício Pereira', '755.709.991-59', 'sergio@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Pietro Rodrigo Lopes', '237.971.762-10', 'pietro@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Bernardo Oliver Assis', '291.614.148-08', 'alana@gmail.com');
INSERT INTO CLIENTE(NOME, CPF, EMAIL) VALUES('Daniela Tereza Alícia Costa', '506.538.403-73', 'alana@gmail.com');


