SELECT * FROM tb_cliente;
SELECT * FROM tb_produto;
SELECT * FROM tb_wishlist;

INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('1', 'Daniela Tereza Alícia Costa', '506.538.403-73', 'alana@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('2', 'João Augusto Cersar', '084.332.196-26', 'joao@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('3', 'Valentina Manuela Silva', '327.327.472-70', 'valentina@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('4', 'Guilherme Enrico Daniel Figueiredo', '248.669.319-06', 'guilherme@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('5', 'Jéssica Helena da Conceição', '272.839.335-49', 'jessica@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('6', 'Raul Mateus Moura', '477.619.930-09', 'raul@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('7', 'Nicolas Cauã Araújo', '154.331.069-93', 'nicolas@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('8', 'Isadora Evelyn Carolina Silveira', '932.956.941-25', 'isadora@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('9', 'Caroline Sarah Silvana Pires', '477.775.029-99', 'carol@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('10', 'Lucas Luan Yuri da Paz', '247.346.367-02', 'lucas@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('11', 'Thiago Cauã Freitas', '375.579.488-82', 'tiago@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('12', 'Sérgio Kauê Benício Pereira', '755.709.991-59', 'sergio@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('13', 'Pietro Rodrigo Lopes', '237.971.762-10', 'pietro@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('14', 'Bernardo Oliver Assis', '291.614.148-08', 'alana@gmail.com');
INSERT INTO tb_cliente(id_cliente, nome, cpf, email) VALUES('15', 'Daniela Tereza Alícia Costa', '506.538.403-73', 'alana@gmail.com');

INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('1','Boneca', 50.00);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('2','Mochila', 90.00);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('3','Livro', 50.00);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('4','Tablet', 850.00);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('5','Drone', 250.00);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('6','Ventilador de mesa', 50.00);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('7','Piscina', 400);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('8','Cerveja Corona', 21);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('9','Ventilador de teto', 190);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('10','Guarda-Roupa 6 portas', 800);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('11','Molho de tomate', 2);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('12','Balança Digital', 97);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('13','Fralda huggies', 33);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('14','Cadeira Gamer', 780);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('15','Aspirador de Pó', 120);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('16','Geladeira', 1900);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('17','Escrivaninha', 300);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('18','Relógio de Pulso', 150);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('19','Escrivaninha Marron', 300);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('20','Cadeira', 190);
INSERT INTO tb_produto(id_produto, nome, valor)  VALUES('21','Notebook', 1900);